#!/bin/bash
echo "Running local CI checks..."

# Используем системный Maven
#mvn spotless:apply

mvn checkstyle:check
if [ $? -ne 0 ]; then
    echo "❌ Checkstyle failed!"
    exit 1
fi

mvn test
if [ $? -ne 0 ]; then
    echo "❌ Tests failed!"
    exit 1
fi

echo "✅ All checks passed!"
